import crypto from "crypto";
import supabase from "../config/Supabase.js";
import { logActivity } from "../utilis/activityLogger.js";
const BUCKET=process.env.SUPABASE_STORAGE_BUCKET||'drive';
const safe=(v)=>String(v||'').replace(/[\\/?%*:|"<>]/g,'_').replace(/\.\.+/g,'.').trim().slice(0,255); const getFile=(id)=>supabase.from('files').select('*').eq('id',id).single();
const canAccess=async(file,userId,needed='viewer')=>{if(file.owner_id===userId)return true;const {data}=await supabase.from('shares').select('role').eq('resource_type','file').eq('resource_id',file.id).eq('grantee_user_id',userId).maybeSingle();return data?.role==='editor'||(data?.role==='viewer'&&needed==='viewer')};
export const uploadFile=async(req,res)=>{try{if(!req.file)return res.status(400).json({error:{code:'FILE_REQUIRED',message:'File is required'}});const folderId=req.body.folderId??req.body.folder_id??null;if(folderId){const {data}=await supabase.from('folders').select('id').eq('id',folderId).eq('owner_id',req.user.id).eq('is_deleted',false).maybeSingle();if(!data)return res.status(404).json({error:{code:'FOLDER_NOT_FOUND',message:'Folder not found'}})}const name=safe(req.file.originalname);const storageKey=`${req.user.id}/${crypto.randomUUID()}-${name}`;const {error:up}=await supabase.storage.from(BUCKET).upload(storageKey,req.file.buffer,{contentType:req.file.mimetype||'application/octet-stream',upsert:false});if(up)throw up;const checksum=crypto.createHash('sha256').update(req.file.buffer).digest('hex');const {data,error}=await supabase.from('files').insert({name,mime_type:req.file.mimetype||'application/octet-stream',size_bytes:req.file.size,storage_key:storageKey,owner_id:req.user.id,folder_id:folderId,checksum,status:'ready'}).select().single();if(error){await supabase.storage.from(BUCKET).remove([storageKey]);throw error}await supabase.from('file_versions').insert({file_id:data.id,version_number:1,storage_key:storageKey,size_bytes:req.file.size,checksum});await logActivity({actorId:req.user.id,action:'upload',resourceType:'file',resourceId:data.id,context:{name:data.name,sizeBytes:data.size_bytes}});res.status(201).json({file:data});}catch(e){res.status(500).json({error:{code:'UPLOAD_FAILED',message:e.message}})}};
export const getFiles=async(req,res)=>{try{const folderId=req.query.folderId??req.query.folder_id;const limit=Math.min(Math.max(Number(req.query.limit)||50,1),100);const page=Math.max(Number(req.query.page)||0,0);let q=supabase.from('files').select('*').eq('owner_id',req.user.id).eq('is_deleted',false);q=folderId?q.eq('folder_id',folderId):q.is('folder_id',null);const sort=req.query.sort==='name'?'name':req.query.sort==='size'?'size_bytes':'updated_at';const ascending=req.query.order==='asc';const {data,error}=await q.order(sort,{ascending}).range(page*limit,(page+1)*limit);if(error)throw error;const rows=data||[];res.json({files:rows.slice(0,limit),pagination:{page,limit,hasMore:rows.length>limit,nextPage:rows.length>limit?page+1:null}})}catch(e){res.status(500).json({error:{code:'FILES_FETCH_FAILED',message:e.message}})}};
export const renameFile=async(req,res)=>{try{const {data:file,error:find}=await getFile(req.params.id);if(find||!file||file.is_deleted)return res.status(404).json({error:{code:'FILE_NOT_FOUND',message:'File not found'}});if(!(await canAccess(file,req.user.id,'editor')))return res.status(403).json({error:{code:'FORBIDDEN',message:'Editor access required'}});const name=safe(req.body.name);if(!name)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'File name is required'}});const {data,error}=await supabase.from('files').update({name,updated_at:new Date().toISOString()}).eq('id',file.id).select().single();if(error)throw error;await logActivity({actorId:req.user.id,action:'rename',resourceType:'file',resourceId:file.id,context:{oldName:file.name,newName:name}});res.json({file:data});}catch(e){res.status(500).json({error:{code:'RENAME_FAILED',message:e.message}})}};
export const moveFile=async(req,res)=>{try{const {data:file,error:find}=await getFile(req.params.id);if(find||!file||file.is_deleted)return res.status(404).json({error:{code:'FILE_NOT_FOUND',message:'File not found'}});if(!(await canAccess(file,req.user.id,'editor')))return res.status(403).json({error:{code:'FORBIDDEN',message:'Editor access required'}});const folderId=req.body.folderId??req.body.folder_id??null;if(folderId){const {data}=await supabase.from('folders').select('id').eq('id',folderId).eq('owner_id',file.owner_id).eq('is_deleted',false).maybeSingle();if(!data)return res.status(404).json({error:{code:'FOLDER_NOT_FOUND',message:'Folder not found'}})}const {data,error}=await supabase.from('files').update({folder_id:folderId,updated_at:new Date().toISOString()}).eq('id',file.id).select().single();if(error)throw error;await logActivity({actorId:req.user.id,action:'move',resourceType:'file',resourceId:file.id,context:{folderId}});res.json({file:data});}catch(e){res.status(500).json({error:{code:'MOVE_FAILED',message:e.message}})}};
export const copyFile=async(req,res)=>{try{const {data:file,error:find}=await getFile(req.params.id);if(find||!file||file.is_deleted)return res.status(404).json({error:{code:'FILE_NOT_FOUND',message:'File not found'}});if(!(await canAccess(file,req.user.id,'editor')))return res.status(403).json({error:{code:'FORBIDDEN',message:'Editor access required'}});const folderId=req.body.folderId??req.body.folder_id??null;if(folderId){const {data:folder}=await supabase.from('folders').select('id').eq('id',folderId).eq('owner_id',req.user.id).eq('is_deleted',false).maybeSingle();if(!folder)return res.status(404).json({error:{code:'FOLDER_NOT_FOUND',message:'Folder not found'}})}const {data:blob,error:downloadError}=await supabase.storage.from(BUCKET).download(file.storage_key);if(downloadError)throw downloadError;const name=safe('Copy of '+file.name);const storageKey=req.user.id+'/'+crypto.randomUUID()+'-'+name;const buffer=Buffer.from(await blob.arrayBuffer());const {error:uploadError}=await supabase.storage.from(BUCKET).upload(storageKey,buffer,{contentType:file.mime_type||'application/octet-stream',upsert:false});if(uploadError)throw uploadError;const {data,error}=await supabase.from('files').insert({name,mime_type:file.mime_type,size_bytes:file.size_bytes,storage_key:storageKey,owner_id:req.user.id,folder_id:folderId,checksum:file.checksum,status:'ready'}).select().single();if(error){await supabase.storage.from(BUCKET).remove([storageKey]);throw error}await supabase.from('file_versions').insert({file_id:data.id,version_number:1,storage_key:storageKey,size_bytes:buffer.length,checksum:file.checksum});await logActivity({actorId:req.user.id,action:'upload',resourceType:'file',resourceId:data.id,context:{name:data.name,sourceFileId:file.id}});res.status(201).json({file:data});}catch(e){res.status(500).json({error:{code:'COPY_FAILED',message:e.message}})}};
export const deleteFile=async(req,res)=>{try{const {data:file,error:find}=await getFile(req.params.id);if(find||!file||file.is_deleted)return res.status(404).json({error:{code:'FILE_NOT_FOUND',message:'File not found'}});if(file.owner_id!==req.user.id)return res.status(403).json({error:{code:'FORBIDDEN',message:'Only the owner can delete a file'}});const {data,error}=await supabase.from('files').update({is_deleted:true,deleted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',file.id).select().single();if(error)throw error;await logActivity({actorId:req.user.id,action:'delete',resourceType:'file',resourceId:file.id,context:{name:file.name}});res.json({file:data});}catch(e){res.status(500).json({error:{code:'DELETE_FAILED',message:e.message}})}};
export const getTrash=async(req,res)=>{try{const {data:files,error}=await supabase.from('files').select('*').eq('owner_id',req.user.id).eq('is_deleted',true).order('updated_at',{ascending:false});if(error)throw error;res.json({files:files||[]});}catch(e){res.status(500).json({error:{code:'TRASH_FETCH_FAILED',message:e.message}})}};
export const restoreFile=async(req,res)=>{try{const {data,error}=await supabase.from('files').update({is_deleted:false,updated_at:new Date().toISOString()}).eq('id',req.params.id).eq('owner_id',req.user.id).eq('is_deleted',true).select().single();if(error||!data)return res.status(404).json({error:{code:'FILE_NOT_FOUND',message:'Deleted file not found'}});await logActivity({actorId:req.user.id,action:'restore',resourceType:'file',resourceId:data.id,context:{name:data.name}});res.json({file:data});}catch(e){res.status(500).json({error:{code:'RESTORE_FAILED',message:e.message}})}};
export const permanentlyDeleteFile=async(req,res)=>{try{const {data:file,error:find}=await getFile(req.params.id);if(find||!file||!file.is_deleted)return res.status(404).json({error:{code:'FILE_NOT_FOUND',message:'Deleted file not found'}});if(file.owner_id!==req.user.id)return res.status(403).json({error:{code:'FORBIDDEN',message:'Only the owner can delete a file'}});await supabase.storage.from(BUCKET).remove([file.storage_key]);const {error}=await supabase.from('files').delete().eq('id',file.id).eq('owner_id',req.user.id);if(error)throw error;res.json({message:'File permanently deleted'});}catch(e){res.status(500).json({error:{code:'PERMANENT_DELETE_FAILED',message:e.message}})}};
export const downloadFile=async(req,res)=>{try{const {data:file,error}=await getFile(req.params.id);if(error||!file||file.is_deleted)return res.status(404).json({error:{code:'FILE_NOT_FOUND',message:'File not found'}});if(!(await canAccess(file,req.user.id,'viewer')))return res.status(403).json({error:{code:'FORBIDDEN',message:'You do not have access to this file'}});const {data,error:signed}=await supabase.storage.from(BUCKET).createSignedUrl(file.storage_key,60);if(signed)throw signed;await logActivity({actorId:req.user.id,action:'download',resourceType:'file',resourceId:file.id,context:{name:file.name}});res.json({file,signedUrl:data.signedUrl,expiresIn:60});}catch(e){res.status(500).json({error:{code:'DOWNLOAD_FAILED',message:e.message}})}};


export const getVersions = async (req, res) => {
  try {
    const { data: file } = await getFile(req.params.id);
    if (!file || !(await canAccess(file, req.user.id, 'viewer'))) return res.status(404).json({ error: { code: 'FILE_NOT_FOUND', message: 'File not found' } });
    const { data, error } = await supabase.from('file_versions').select('*').eq('file_id', file.id).order('version_number', { ascending: false });
    if (error) throw error;
    res.json({ versions: data || [] });
  } catch (e) { res.status(500).json({ error: { code: 'VERSIONS_FETCH_FAILED', message: e.message } }); }
};

export const revertVersion = async (req, res) => {
  try {
    const { data: file } = await getFile(req.params.id);
    if (!file || !(await canAccess(file, req.user.id, 'editor'))) return res.status(403).json({ error: { code: 'FORBIDDEN', message: 'Editor access required' } });
    const { data: version } = await supabase.from('file_versions').select('*').eq('id', req.params.versionId).eq('file_id', file.id).single();
    if (!version) return res.status(404).json({ error: { code: 'VERSION_NOT_FOUND', message: 'Version not found' } });
    const { data: blob, error: downloadError } = await supabase.storage.from(BUCKET).download(version.storage_key);
    if (downloadError) throw downloadError;
    const nextKey = req.user.id + '/' + crypto.randomUUID() + '-' + safe(file.name);
    const buffer = Buffer.from(await blob.arrayBuffer());
    const { error: uploadError } = await supabase.storage.from(BUCKET).upload(nextKey, buffer, { contentType: file.mime_type || 'application/octet-stream', upsert: false });
    if (uploadError) throw uploadError;
    const { data: updated, error } = await supabase.from('files').update({ storage_key: nextKey, size_bytes: buffer.length, checksum: crypto.createHash('sha256').update(buffer).digest('hex'), updated_at: new Date().toISOString() }).eq('id', file.id).select().single();
    if (error) throw error;
    await logActivity({ actorId: req.user.id, action: 'restore', resourceType: 'file', resourceId: file.id, context: { versionId: version.id } });
    res.json({ file: updated });
  } catch (e) { res.status(500).json({ error: { code: 'VERSION_REVERT_FAILED', message: e.message } }); }
};




