import supabase from "../config/Supabase.js";
import { logActivity } from "../utilis/activityLogger.js";
const clean = (value) => String(value || '').replace(/[\\/?%*:|"<>]/g, '_').replace(/\.\.+/g, '.').trim().slice(0, 120);
const findFolder = (id, userId, includeDeleted = false) => { let q = supabase.from('folders').select('*').eq('id', id).eq('owner_id', userId); if (!includeDeleted) q = q.eq('is_deleted', false); return q.single(); };
export const createFolder = async (req, res) => { try { const name=clean(req.body.name), parentId=req.body.parentId ?? req.body.parent_id ?? null; if(!name) return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Folder name is required'}}); if(parentId){const {data:parent}=await findFolder(parentId,req.user.id);if(!parent)return res.status(404).json({error:{code:'PARENT_NOT_FOUND',message:'Parent folder not found'}})} const {data,error}=await supabase.from('folders').insert({name,owner_id:req.user.id,parent_id:parentId}).select().single(); if(error)return res.status(409).json({error:{code:'FOLDER_CREATION_FAILED',message:error.message}}); await logActivity({actorId:req.user.id,action:'upload',resourceType:'folder',resourceId:data.id,context:{name:data.name}}); res.status(201).json({folder:data}); } catch(e){res.status(500).json({error:{code:'SERVER_ERROR',message:e.message}})} };
export const getFolders = async (req,res) => { try { const parentId=req.query.parentId ?? req.query.parent_id; let q=supabase.from('folders').select('*').eq('owner_id',req.user.id).eq('is_deleted',false); q=parentId?q.eq('parent_id',parentId):q.is('parent_id',null); const {data,error}=await q.order('name'); if(error)throw error; res.json({folders:data||[]}); } catch(e){res.status(500).json({error:{code:'FOLDERS_FETCH_FAILED',message:e.message}})} };
export const renameFolder = async (req,res) => { try { const name=clean(req.body.name); if(!name)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Folder name is required'}}); const {data,error}=await supabase.from('folders').update({name,updated_at:new Date().toISOString()}).eq('id',req.params.id).eq('owner_id',req.user.id).eq('is_deleted',false).select().single(); if(error||!data)return res.status(404).json({error:{code:'FOLDER_NOT_FOUND',message:'Folder not found'}}); res.json({folder:data}); }catch(e){res.status(500).json({error:{code:'RENAME_FAILED',message:e.message}})} };
export const moveFolder = async (req,res) => { try { const parentId=req.body.parentId ?? req.body.parent_id ?? null; if(parentId===req.params.id)return res.status(400).json({error:{code:'CYCLE_DETECTED',message:'A folder cannot contain itself'}}); if(parentId){const {data:parent}=await findFolder(parentId,req.user.id);if(!parent)return res.status(404).json({error:{code:'PARENT_NOT_FOUND',message:'Parent folder not found'}})} const {data,error}=await supabase.from('folders').update({parent_id:parentId,updated_at:new Date().toISOString()}).eq('id',req.params.id).eq('owner_id',req.user.id).eq('is_deleted',false).select().single(); if(error||!data)return res.status(404).json({error:{code:'FOLDER_NOT_FOUND',message:'Folder not found'}}); await logActivity({actorId:req.user.id,action:'move',resourceType:'folder',resourceId:data.id,context:{parentId}}); res.json({folder:data}); }catch(e){res.status(500).json({error:{code:'MOVE_FAILED',message:e.message}})} };
export const deleteFolder = async (req,res) => { try { const {data,error}=await supabase.from('folders').update({is_deleted:true,updated_at:new Date().toISOString()}).eq('id',req.params.id).eq('owner_id',req.user.id).eq('is_deleted',false).select().single(); if(error||!data)return res.status(404).json({error:{code:'FOLDER_NOT_FOUND',message:'Folder not found'}}); await supabase.from('files').update({is_deleted:true}).eq('folder_id',data.id).eq('owner_id',req.user.id).eq('is_deleted',false); await logActivity({actorId:req.user.id,action:'delete',resourceType:'folder',resourceId:data.id,context:{name:data.name}}); res.json({folder:data}); }catch(e){res.status(500).json({error:{code:'DELETE_FAILED',message:e.message}})} };
export const getTrashFolders = async (req,res) => { try { const {data,error}=await supabase.from('folders').select('*').eq('owner_id',req.user.id).eq('is_deleted',true).order('updated_at',{ascending:false}); if(error)throw error; res.json({folders:data||[]}); }catch(e){res.status(500).json({error:{code:'TRASH_FETCH_FAILED',message:e.message}})} };
export const restoreFolder = async (req,res) => { try { const {data,error}=await supabase.from('folders').update({is_deleted:false,updated_at:new Date().toISOString()}).eq('id',req.params.id).eq('owner_id',req.user.id).eq('is_deleted',true).select().single(); if(error||!data)return res.status(404).json({error:{code:'FOLDER_NOT_FOUND',message:'Deleted folder not found'}}); await supabase.from('files').update({is_deleted:false}).eq('folder_id',data.id).eq('owner_id',req.user.id); await logActivity({actorId:req.user.id,action:'restore',resourceType:'folder',resourceId:data.id,context:{name:data.name}}); res.json({folder:data}); }catch(e){res.status(500).json({error:{code:'RESTORE_FAILED',message:e.message}})} };

