import supabase from "../config/Supabase.js";
import { logActivity } from "../utilis/activityLogger.js";
const resourceTable=(type)=>type==='file'?'files':'folders';
const resource=async(type,id)=>supabase.from(resourceTable(type)).select('id,owner_id,is_deleted').eq('id',id).single();
export const createShare=async(req,res)=>{try{const type=req.body.resourceType??req.body.resource_type,id=req.body.resourceId??req.body.resource_id,grantee=req.body.granteeUserId??req.body.grantee_user_id,role=req.body.role;if(!['file','folder'].includes(type)||!id||!grantee||!['viewer','editor'].includes(role))return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'resourceType, resourceId, granteeUserId and a valid role are required'}});const {data:item,error:find}=await resource(type,id);if(find||!item||item.is_deleted)return res.status(404).json({error:{code:'RESOURCE_NOT_FOUND',message:'Resource not found'}});if(item.owner_id!==req.user.id)return res.status(403).json({error:{code:'FORBIDDEN',message:'Only the owner can create shares'}});const {data,error}=await supabase.from('shares').upsert({resource_type:type,resource_id:id,grantee_user_id:grantee,role,created_by:req.user.id},{onConflict:'resource_type,resource_id,grantee_user_id'}).select().single();if(error)throw error;await logActivity({actorId:req.user.id,action:'share',resourceType:type,resourceId:id,context:{granteeUserId:grantee,role}});res.status(201).json({share:data});}catch(e){res.status(500).json({error:{code:'SHARE_FAILED',message:e.message}})}};
export const getShares=async(req,res)=>{try{const type=req.params.resourceType,id=req.params.resourceId;const {data:item,error:find}=await resource(type,id);if(find||!item)return res.status(404).json({error:{code:'RESOURCE_NOT_FOUND',message:'Resource not found'}});const {data,error}=await supabase.from('shares').select('*').eq('resource_type',type).eq('resource_id',id);if(error)throw error;res.json({shares:data||[]});}catch(e){res.status(500).json({error:{code:'SHARES_FETCH_FAILED',message:e.message}})}};
export const deleteShare=async(req,res)=>{try{const {data:share,error:find}=await supabase.from('shares').select('*').eq('id',req.params.shareId).single();if(find||!share)return res.status(404).json({error:{code:'SHARE_NOT_FOUND',message:'Share not found'}});const {data:item,error:itemError}=await resource(share.resource_type,share.resource_id);if(itemError||!item||item.owner_id!==req.user.id)return res.status(403).json({error:{code:'FORBIDDEN',message:'Only the owner can revoke this share'}});const {error}=await supabase.from('shares').delete().eq('id',share.id);if(error)throw error;res.json({message:'Share revoked',share});}catch(e){res.status(500).json({error:{code:'SHARE_DELETE_FAILED',message:e.message}})}};

export const getSharedWithMe = async (req,res) => { try { const { data, error } = await supabase.from('shares').select('*').eq('grantee_user_id', req.user.id); if (error) throw error; res.json({ shares: data || [] }); } catch (e) { res.status(500).json({ error: { code: 'SHARED_FETCH_FAILED', message: e.message } }); } };

